# Generated by Django 3.2 on 2021-06-24 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcamera',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addcamera',
            name='Camera_Number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='addcamera',
            name='Ip_Adderss',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='addcamera',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='addcamera',
            name='Password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
